#!/bin/bash

set -e

case "$1" in
    configure|reconfigure)
        adduser --system --quiet --home /nonexistent --no-create-home --group jmxtrans
        chown jmxtrans:jmxtrans /var/log/jmxtrans
        chown jmxtrans:jmxtrans /etc/jmxtrans
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
