#!/bin/bash

set -e

case "$1" in
    purge)
        if [ -x "$(command -v deluser)" ]; then
            rm -rf /var/log/jmxtrans
            deluser --quiet --system jmxtrans > /dev/null || true
            deluser --group --system --quiet --only-if-empty jmxtrans || true
        else
            echo >&2 "not removing jmxtrans system account, group and logfiles because deluser command was not found"
        fi
    ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
